version: "3.9"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    ports:
      - "${N8N_PORT:-5678}:5678"

    env_file:
      - .env

    environment:
      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: ${N8N_PORT:-5678}
      N8N_PROTOCOL: ${N8N_PROTOCOL:-http}
      N8N_SECURE_COOKIE: ${N8N_SECURE_COOKIE:-false}

      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE:-Asia/Dhaka}
      TZ: ${TZ:-Asia/Dhaka}

      DB_TYPE: ${DB_TYPE:-sqlite}

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
